# Generated by Django 5.1.3 on 2024-11-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_remove_book_author_remove_book_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalog.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                help_text="Select a genre for this book", to="catalog.genre"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                default="0000000000000",
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(
                default="No summary available",
                help_text="Enter a brief description of the book",
                max_length=1000,
            ),
        ),
    ]
